name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python dependencies, add alias.
      run: make setup 
    - name: Compile 
      run: make
